/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const after_Purchases_Create = require('./code/after-purchases-create');
const before_Redemptions_Create = require('./code/before-redemptions-create');

class first_projectSrv extends LCAPApplicationService {
    async init() {

        this.after('CREATE', 'Purchases', async (results, request) => {
            await after_Purchases_Create(results, request);
        });

        this.before('CREATE', 'Redemptions', async (request) => {
            await before_Redemptions_Create(request);
        });

        return super.init();
    }
}


module.exports = {
    first_projectSrv
};